### ISSUE TITLE
docs ToDo list

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/docs-archive#6]
ToDo list:

- [ ] write a hands-on tutorial (use game ID 10971, from NES database).
- [ ] guidelines for translations
- [x] create a page explaining the Memory Inspector, similar to what Scott did in the past [with this forum post](http://retroachievements.org/viewtopic.php?t=96). Don't forget to add the features added recently by @GameDragon2k .

**Comment by meleu** [comment]
I'm going to break this into separate issues...
